README.md
config.go
events/api.go
events/events.go
events/mqtt.go
example-config.yml
main.go

Added support for excluding cameras from alerting - to remove noise if not all cameras need to generate notifications.
Example config:
```yaml
cameras:
exclude:
- test_cam_01
- test_cam_02
```
Also includes minor adjustments to README & a fix for web API polling interval.
closes #2

Add camera exclusions

---

notifier/smtp.go

Updated SMTP client for email alerting to use `NoTLS` if `SMTPTLS` config flag is set.
Should fix #16

(fix) Allow SMTP without TLS

---

notifier/alerts.go

Resolves an issue where Frigate snapshot wasn't being copied if multiple alert methods were configured. Only the first alert would get a copy of the screenshot.

(fix) resolve issue with snapshot not working with multiple alert methods configured

---

README.md
docs/index.md
mkdocs.yml

Updated README a bit to link to the docs site now. Added automatic toggle for light/dark mode in docs

Update README to link to docs & minor docs adjustment

---

docs/changelog.md
events/mqtt.go
notifier/alerts.go

Reported in #24 - App would crash if a snapshot wasn't included.
This double-checks that snapshot is not `nil` before attempting to read it.

Fixed crash if Frigate has no event info & app couldn't pull snapshots

---

docs/CNAME

GitHub pages was overwriting custom CNAME for docs on every deploy. Turns out it needs a custom `CNAME` file in the docs root to prevent this. Adding that file here...

Add gh-pages CNAME

---

.github/workflows/docker-publish.yml

Update cosign to latest to fix docker build error: 
```text
getting signer: getting key from Fulcio: getting CTFE public keys: updating local metadata and targets: error updating to TUF remote mirror: invalid key 
```

Bump cosign version

---

README.md
config/config.go
docs/changelog.md
docs/config.md
docs/index.md
events/api.go
example-config.yml
go.mod
go.sum
notifier/alerts.go
notifier/pushover.go
notifier/telegram.go

Added support for notifications via Pushover

Add pushover support

---

Dockerfile
docs/changelog.md

Revised docker build to include multistage build. 
This reduced the container size from around 1Gb to ~11Mb.

Reduce docker image size

---

.github/FUNDING.yml
Dockerfile
config/config.go
docker-compose.yml
docs/changelog.md
docs/config.md
docs/install.md
events/api.go
events/events.go
events/mqtt.go
example-config.yml
main.go
notifier/alerts.go
notifier/discord.go
notifier/gotify.go
notifier/pushover.go
notifier/smtp.go
notifier/telegram.go

This PR fixes issues with the zone filter raised in #37. Originally, this was built to only alert on new events from Frigate. However, Frigate will send updated event notifications to MQTT upon certain things, like the detected object moving to a different zone. 
So with the zone filter built as it was originally, the app would only send an event if there was a **new** event that contained a zone. If an event started with no zone info, and was updated later, no notification would be sent. App code adjusted to account for event updates, and compare zone details. New alerts will only be sent if the object enters a new zone & also that zone is on the allowed notification list. 
Also added the ability to provide custom date / time formats to be used in the notifications. And cleaned up some …

Fix zone issue

---

config/config.go
docs/changelog.md
docs/config.md
events/mqtt.go
example-config.yml

Add new `topic_prefix` config item under frigate > mqtt. This overrides the default `frigate` MQTT topic. 
Events are subscribed at `<topic_prefix>/events`
Original Request: #41

Allow changing default MQTT topic prefix via config (#41)

---

config/config.go
docs/changelog.md
docs/config.md
events/api.go
events/events.go
events/mqtt.go
example-config.yml
main.go

Adds new event filtering based on detection label. Implementation similar to zone filtering. 
New config section to `allow` or `block` labels. 
- Allow acts as permit filter. If left empty, labels are not checked & events are sent. If specified, only configured labels will generate alerts. 
- Block list will always filter any listed labels, even if permitted by allow list
Also bump app version to v0.2.7 for release
Original request: #40

Add label filtering

---

docs/config.md

Quick update to empty sample config file in docs - add label allow/block section that was just introduced.

Add label config to sample config in docs

---

README.md
config/config.go
docs/changelog.md
docs/config.md
docs/index.md
example-config.yml
notifier/alerts.go
notifier/gotify.go
notifier/nfty.go
util/httpclient.go

Add support for notifications via Nfty
Original request #45

Add nfty support

---

config/config.go
docs/changelog.md
docs/config.md
events/api.go
example-config.yml
notifier/alerts.go
notifier/gotify.go
notifier/nfty.go
util/httpclient.go

Add support for sending arbitrary HTTP headers to Frigate. This allows for ability to send authorization headers, or others if needed.
Original request #52

Add frigate auth headers

---

config/config.go
docs/changelog.md
docs/config.md
events/api.go
events/events.go
events/mqtt.go
example-config.yml
models/event.go
notifier/alerts.go
notifier/discord.go
notifier/gotify.go
notifier/nfty.go
notifier/pushover.go
notifier/smtp.go
notifier/telegram.go
templates/html.template
templates/markdown.template
templates/plaintext.template
util/httpclient.go

Previously, notifications were manually built by appending strings, then manual modifications within some notification providers to account for their needs. This PR switches to using go templates & includes 3 default templates: markdown, plaintext, and HTML. Re-worked notifications to use the new template system.
This will hopefully make notifications more uniform & starts the work needed to implement #44

Notif templates

---

Dockerfile
config/config.go
docs/changelog.md
docs/config.md
events/api.go
events/events.go
events/mqtt.go
example-config.yml
go.mod
go.sum
main.go
models/event.go
models/stats.go
notifier/alerts.go
notifier/discord.go
notifier/gotify.go
notifier/nfty.go
notifier/pushover.go
notifier/smtp.go
notifier/telegram.go
templates/html.template
templates/markdown.template
templates/plaintext.template
util/httpclient.go

Bunch of misc fixes/adjustments/enhancements:
- Update docs regarding Frigate `server` config (#56)
- Fix default web API query interval (#55)
- Add new `public_url` config item for Frigate (#52)
- Add startup check to ensure Frigate is reachable & validate configured IP/hostname/URL (#56)
- Fix 0% label scores when using web API to query events (#54)
- Remove markdown dependency, which is no longer needed after implementing templates for notifications (#59)
This should wrap up work for version 0.2.8 🥳

Minor fixes

---

.dockerignore
.github/workflows/docker-publish.yml
config/config.go

First of all, thank you so much for making this!
I'm introducing this change because I was getting the `Failed to load config file!` error on startup with a `docker-compose.yml` configured as such:
```yml
services:
frigate:
...
mqtt:
...
frigate-notify:
image: ghcr.io/0x2142/frigate-notify:v0.3.1
depends_on: [mqtt, frigate]
restart: unless-stopped
environment:
FN_FRIGATE_SERVER: http://frigate:5000
FN_FRIGATE_MQTT_ENABLED: 'true'
FN_FRIGATE_MQTT_SERVER: mqtt
FN_FRIGATE_CAMERAS_EXCLUDE: '[some_room]'
FN_ALERTS_PUSHOVER_ENABLED: 'true'
FN_ALERTS_PUSHOVER_USERKEY: ${FN_ALERTS_PUSHOVER_USERKEY}
FN_ALERTS_PUSHOVER_TOKEN: ${FN_ALERTS_PUSHOVER_TOKEN}
```
I'm not really in a position to store configs on the host machine so a volume-mounted config file was a no-go.
I've temporarily solved that …

Allow configuration from environment variables only

---

docs/changelog.md
docs/config/templates.md
notifier/alerts.go

Environment variables can now be retrieved using `env`, for example: `{{ env  "FN_SOME_ENV }}`
Accessed variables must be prefixed with `FN_`

Add ability to include env vars in templates

---

events/api.go
events/mqtt.go
notifier/alerts.go
notifier/gotify.go

Update Gotify to use `public_url` for the snapshot image, when it is configured. Most other alert profiles are already using this as defined in the message templates, but other methods are able to directly upload snapshot image. Gotify requires attaching the snapshot by providing a direct link which is being manually appended to the message, so this got missed. Fixed now though!
(#142)

Fix gotify snap url

---

main.go

Setting `loglevel` via CLI argument wasn't working & also `trace` logs didn't include calling module info.

Fix issue with loglevel

---

Dockerfile
LICENSE
api/v1/notiftest.go
config/internal.go
docs/changelog.md
events/events.go
events/reviews.go
go.mod
models/event.go
notifier/alerts.go
notifier/filters.go
templates/html.template
templates/markdown.template
templates/plaintext.template

Early support for /reviews included using only the first detection as a basis for notifications, but all events in a review would pass through global filters. With addition of alert-level filtering, this meant that only the first detection would make it to the notifications - so a review item with multiple events might be not notify, if the qualifying event was not the first in the review

Fix issue with alerts for multi-event review items

---

docs/changelog.md
docs/config/file.md
docs/config/sample.md
example-config.yml
go.mod
go.sum
models/config.go
notifier/telegram.go

Old Telegram SDK not maintained any longer, swapping to better fork. Added support for `message_thread_id` in Telegram notifs

Swap telegram sdk

---

notifier/alerts.go

This pull request enhances the `GetClip` function in `notifier/alerts.go` to improve handling of scenarios where a clip is not immediately available. The most important change introduces a retry mechanism with logging to wait for the clip to be processed.
* [`notifier/alerts.go`](diffhunk://#diff-6c7785c677e6f734e3d5fc0e1d1ac809e5da51394255d2f8ca982755de92221bR240-R253): Added a retry mechanism to handle cases where the clip is still being processed by Frigate. This includes waiting for 2 seconds between attempts, incrementing the attempt counter, and logging the retry status. A debug log is also added to indicate when the clip becomes available.

fix: check if downloaded clip is empty
