.github/workflows/docker-publish.yml
.github/workflows/go-release.yml

Adding workflows for GitHub actions to make package deployment easier.
Added:
- Docker image build & deployment
- Goreleaser package deployment

GitHub Actions support

---

.github/workflows/docker-publish.yml
.github/workflows/go-release.yml

Fix actions to only run on tagged release

---

LICENSE
README.md
config.go
docker-compose.yml
events/mqtt.go
example-config.yml
notifier/alerts.go
notifier/discord.go
notifier/gotify.go
notifier/smtp.go

Handful of minor updates & fixes that I've been meaning to work on...

Misc updates

---

notifier/discord.go

Change to use Discord embeds
closes #9

Migrate discord messages to use embeds

---

Dockerfile

Update to docker image that supports golang 1.21.x

Update docker image version

---

config/config.go

Fix issue where config file was not being properly loaded if default location was overridden by environment variable

Fix config file load if specified by ENV

---

docs/config.md
docs/index.md

Update docs to better explain how zone detection events are processed

Minor docs updates

---

docs/config/index.md

- Minor change to wording on config docs

adjust config docs

---

.github/workflows/docker-publish.yml
README.md
config/config.go
docs/changelog.md
docs/config/file.md
docs/config/options.md
docs/config/sample.md
docs/index.md
example-config.yml
main.go
models/event.go
notifier/alerts.go
notifier/discord.go
notifier/gotify.go
notifier/nfty.go
notifier/smtp.go
notifier/telegram.go
templates/html.template
templates/json.template
templates/markdown.template
templates/plaintext.template

A number of changes / fixes, including:
- Updating camera links for Frigate 0.14.0+
- Fix ntfy action button not using `public_url` when configured (#79)
- Add HTTP headers to ntfy for auth (#82)
- Add config option to drop events without a snapshot
- Move additional notification elements to templates
- Fix misspelling of ntfy
- Add support for disabling color on console logs
- Other minor logging enhancements
- Set up for `dev` branch build

Misc fixes

---

docs/changelog.md
docs/install.md
main.go

- Update docs
- Update version number

update docs & version for v0.3.1 release

---

config/config.go
docs/changelog.md
docs/config/file.md
docs/config/sample.md
events/api.go
events/filters.go
events/mqtt.go
example-config.yml
main.go
models/event.go

Introducing a few additional filtering options for alerts:
- Sublabels
- Minimum label score
- Quiet hours

Add new alert filters

---

config/config.go
docs/changelog.md
docs/config/file.md
docs/config/sample.md
docs/config/templates.md
events/api.go
example-config.yml
notifier/alerts.go
notifier/nfty.go
notifier/webhook.go
util/httpclient.go

- Add snapshot modifiers (Bounding box, crop, timestamp)
- Allow template variables to be used on HTTP headers
- Document issue where templates cannot start with a variable unless quoted
- Add retry to notifications sent via HTTP

Misc enhancements

---

docs/changelog.md
events/api.go
events/filters.go
main.go

Release v0.3.4

---

config/config.go
docs/changelog.md
docs/config/file.md
docs/config/sample.md
events/cache.go
events/cache_test.go
events/filters.go
example-config.yml

New config option - Only generate notifications once per Frigate event

Add option for single notification per event

---

docs/config/options.md
events/api.go
events/cache.go
events/filters.go
events/mqtt.go
main.go
notifier/discord.go
notifier/pushover.go
notifier/smtp.go
notifier/telegram.go
util/httpclient.go

Adds support for specifying logging level by environment variable or commandline flag. Added trace logging where applicable to include sent/received payloads.
(#129)

Logging improvements

---

LICENSE
docs/changelog.md
main.go

Update app version & changelog date to prepare for release

update app version

---

README.md
config/config.go
docs/changelog.md
docs/config/file.md
docs/config/sample.md
docs/index.md
events/mqtt.go
example-config.yml
notifier/alerts.go
notifier/discord.go
notifier/gotify.go
notifier/nfty.go
notifier/pushover.go
notifier/smtp.go
notifier/telegram.go
notifier/webhook.go

- Add custom sounds for Pushover
- Improve logging for custom rendered content (messages, headers, HTTP params, message title, etc)
- Add error for `reviews` mode if Frigate is not v0.14 or higher

Misc additions

---

Dockerfile
config/config.go
config/validate.go
config/validate_test.go
events/filters.go
notifier/alerts.go

Re-worked config file validation to separate out individual validation components. Easier then to write tests against each piece, and should help later on if I need to re-validate any individual piece of the config (like if there was a change via the future API, for example)

Config validation updates

---

events/events.go
events/filters.go
events/reviews.go

Fix issue with `top_score` in notifications incorrectly showing as `0%`

fix issue with score percent in notifs being 0%

---

.gitignore

Initial gitignore and adds Go workspace files to dockerignore

Initial gitignore

---

Dockerfile

Expose of API port added in Docker image.

Expose of API port

---

config/validate.go
docs/changelog.md
docs/config/file.md
docs/config/sample.md
events/filters.go
events/reviews.go
example-config.yml
models/config.go
models/event.go
models/reviews.go
templates/html.template
templates/json.template
templates/markdown.template
templates/plaintext.template

Fix processing for audio events to include details in notifications
Add config option for filtering audio-only events

Support audio events & filtering

---

config/internal.go
config/validate_test.go
docs/changelog.md
models/config.go

- Update app version
- Set release date in changelog
- Set `reviews` mode to the default

Update App version / changelog for release

---

README.md
config/validate.go
docs/changelog.md
docs/config/file.md
docs/config/sample.md
docs/index.md
example-config.yml
models/config.go
models/internal.go
notifier/alerts.go
notifier/filters.go
notifier/signal.go

Add support for notifications via Signal
**NOTE:** This requires https://github.com/bbernhard/signal-cli-rest-api to be running locally

Add support for Signal

---

notifier/pushover.go

This adds a button to the push notif for the review/event link, similar to Ntfy

Add review/event links as Pushover supplementary URL (#235)

---

config/internal.go
docs/changelog.md
docs/config/file.md

Update docs / changelog / version

---

.github/workflows/go-release.yml
.goreleaser.yaml

Update goreleaser github action & add `.goreleaser.yaml` config to accommodate build modifications for matrix support

Update & fix goreleaser

---

config/config.go
config/providers/env/env.go
config/providers/secrets/secrets.go
docs/changelog.md
docs/config/file.md

Add support for loading config via docker secrets

Add support for docker secrets (#251)

---

docs/changelog.md
docs/config/file.md
docs/config/sample.md
example-config.yml
models/config.go
notifier/alerts.go
notifier/telegram.go

Add ability to grab higher resolution snapshot from camera recording stream
Add ability to send video clip to Telegram instead of snapshot

Updates to snapshot / clip

---

notifier/telegram.go

Fix issue with sending video clip to Telegram that may cause app crash.

Fix Telegram clip crash

---

config/internal.go
docs/changelog.md

Update `dev` version to `v0.5.3-dev` and start new changelog for next release

Update dev version
